import sql from "k6/x/sql";
import driver from "k6/x/sql/driver/hdb";
import secrets from 'k6/secrets';


//get information from secret
const hanaHost = "10.0.0.184"
const hanaPort = "30015";
const hanaDB = "HB1";
const username = "SYSTEM"
const password = "Pandas99";
const db = sql.open(driver, `hdb://${username}:${password}@${hanaHost}:${hanaPort}`);

export function setup() {
  db.exec(`
  CREATE COLUMN TABLE test_table_3 (
    A INT GENERATED BY DEFAULT AS IDENTITY,
    B TEXT,
    C INT,    /* Random integer */
    D DECIMAL(10,2)  /* Random decimal */
    );
  `);
}

export let options = {
  vus: 30,  // 30 virtual users
  duration: '30s' // 30 seconds
}

export default function () {
  // Generate random numbers
  const randomInt = Math.floor(Math.random() * 1000);        // Random integer between 0 and 999
  const randomDecimal = Math.random() * 100;                 // Random decimal between 0 and 99.99
  const formattedDecimal = randomDecimal.toFixed(2);        // Format to 2 decimal places
  const randomText = `Value-${Math.floor(Math.random() * 100)}`; // Random text with number
  // first insert
  let insert_result = db.exec(`
    INSERT INTO test_table_3 (B, C, D)
    VALUES ('${randomText}', ${randomInt}, ${formattedDecimal});
  `);
  console.log(`Row inserted with values: Text=${randomText}, Int=${randomInt}, Decimal=${formattedDecimal}`);

  // then select
  let selectResult = db.query(`
    SELECT * FROM test_table_3
    LIMIT 10;
  `);
  console.log(`Read ${selectResult.length} rows`);
}

export function teardown() {
   db.exec(`DROP TABLE test_table_3;`);
   db.close();
 }