import sql from "k6/x/sql";
import driver from "k6/x/sql/driver/hdb";
import secrets from 'k6/secrets';


//get information from secret
const hanaHost = await secrets.get('hanaHost');
const hanaPort = await secrets.get('hanaPort');
const hanaDB = await secrets.get('hanaDB');
const username = await secrets.get('username');
const password = await secrets.get('password');
//build the connection string
const db = sql.open(driver, `hdb://${username}:${password}@${hanaHost}:${hanaPort}`);

// write your load testing logic

export function setup() {
  db.exec(`
  CREATE COLUMN TABLE test_table2 (
    A INT GENERATED BY DEFAULT AS IDENTITY,
    B TEXT);
  `);
}

export function teardown() {
  db.exec(`
    DROP TABLE test_table2;
  `);
  db.close();
}

export default function () {
  let result = db.exec(`
    INSERT INTO test_table2 (B) VALUES ('One');
  `);
  console.log(`${result.rowsAffected()} rows inserted`);
  
  let rows = db.query("SELECT * FROM test_table2 WHERE B = 'One'");
  for (const row of rows) {
    console.log(`key: ${row.A}, value: ${row.B}`);
  }  
}
